[global]
developmentMode = false
dataFrameSerialization = "legacy"

[server]
port = 8888
address = "localhost"
headless = false
runOnSave = true
allowRunOnSave = true
fileWatcherType = "auto"
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8888

[theme]
base = "dark"


[client]
showErrorDetails = true
toolbarMode = "auto"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s" 